pipeline {
    agent any 
    
    tools {
        maven 'Maven_test'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Archive Artifacts') {
            steps {
               archiveArtifacts artifacts: 'target/my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
